apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-topic-operator
  labels:
    app: strimzi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/eks-topic-operator-role
